### ISSUE TITLE
Incorrect link for "Suggestions and ideas"

### ISSUE THREAD

**Issue by James103** [JGRennison/OpenTTD-patches#328]
## Version of OpenTTD
aff6dbec2d3331b7409119b1ceb9c53ae2fcef9b

## Expected result
The link should point to: https://www.tt-forums.net/viewtopic.php?f=33&t=73469

## Actual result
The link actually points to: https://www.tt-forums.net/viewforum.php?f=32

## Steps to reproduce
Click "New Issue".
On the choose a template page, click "Open" on the right of the row titled "Suggestions and ideas?".
You are redirected to TT-Forms and "OpenTTD Suggestions", not OpenTTD Development > "JGR's Patch Pack".

### New content of `.github/ISSUE_TEMPLATE/config.yml`
```yaml
blank_issues_enabled: false
contact_links:
- name: Suggestions and ideas?
  url: https://www.tt-forums.net/viewtopic.php?f=33&t=73469
  about: Have a suggestion or an idea for a cool new feature? Post them on our forum!
```
